version: "3"

services:
  node1:
    build: .
    image: raftnode:test
    cap_add:
      - NET_ADMIN
    ports:
      - "8081:8080"
      - "9091:9090"
    networks:
      raftcluster:
        ipv4_address: 172.18.0.21
    command: ["1","2,3"]
  node2:
    image: raftnode:test
    cap_add:
      - NET_ADMIN
    ports:
      - "8082:8080"
      - "9092:9090"
    networks:
      raftcluster:
        ipv4_address: 172.18.0.22
    command: ["2","1,3"]
  node3:
    image: raftnode:test
    cap_add:
      - NET_ADMIN
    ports:
      - "8083:8080"
      - "9093:9090"
    networks:
      raftcluster:
        ipv4_address: 172.18.0.23
    command: ["3","1,2"]

networks:
  raftcluster:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
